### PR TITLE
Fix issues #64 and #70

### PR DESCRIPTION
**Pull request by dvandyk**

### CODE REVIEW

**Comment by dvandyk** [comment]
FFS. In the ``manylinux2014`` image the GSL version is so old (< 2.2) that the new function ``gsl_linalg_cholesky_decomp1`` is not available.

Suggestions?

**Comment by mreboud** [comment]
`gsl_linalg_cholesky_decomp` without the 1 is there for backward compatibility so it should be linked to `gsl_linalg_cholesky_decomp1` when it exists and the old method otherwise, no?

**Comment by dvandyk** [comment]
> `gsl_linalg_cholesky_decomp` without the 1 is there for backward compatibility so it should be linked to `gsl_linalg_cholesky_decomp1` when it exists and the old method otherwise, no? see https://github.com/ampl/gsl/blob/a367169b777cdaf98a7b54a91daac007f56875b6/linalg/cholesky.c#L55

See the next line! ``It will be removed in a future release.``

I think I'll add a ``#define GSL_LINALG_CHOLESKY_DECOMP`` that points to the old method if the GSL version is 2.1 or older, and to the new method otherwise.

**Comment by mreboud** [comment]
> > `gsl_linalg_cholesky_decomp` without the 1 is there for backward compatibility so it should be linked to `gsl_linalg_cholesky_decomp1` when it exists and the old method otherwise, no? see https://github.com/ampl/gsl/blob/a367169b777cdaf98a7b54a91daac007f56875b6/linalg/cholesky.c#L55
> 
> See the next line! `It will be removed in a future release.`
> 
> I think I'll add a `#define GSL_LINALG_CHOLESKY_DECOMP` that points to the old method if the GSL version is 2.1 or older, and to the new method otherwise.

Yes I don't see any other solution...

**Pull request merged**
