### PR TITLE
Fix building in environment with non-standard yaml-cpp location

### PR DESCRIPTION
**Pull request by dvandyk**
@daritter Please check if this works for you, and approve.

### CODE REVIEW

**Comment by daritter** [comment]
I will probably not be able to test before next week, sorry

**Comment by dvandyk** [comment]
@daritter ping! :-)

**Comment by dvandyk** [comment]
@daritter Ping!

**Comment by daritter** [comment]
Since there were some other problems as well I created pr #116 which contains this commit among other things

**Comment by dvandyk** [comment]
Closed in lieu of #116.

**Pull request closed without merging**
