### PR TITLE
Goodness of fit

### PR DESCRIPTION
**Pull request by dvandyk**
First steps in replacing LogPosterior::goodness_of_fit with a dedicated class.

Goals:
 - to work with different types of test statistics;
 - to use a ```LogLikelihoodBlock```'s primary test statistic;
 - to display the contents conveniently in Jupyter.

Currently supports only ```ChiSquare``` and ```Empty``` test statistics.

Also fixed some bugs in d.o.f. for ```B->pi``` form factor constraints, and added the ```Analysis``` and
```BestFitPoint``` Python classes.

Jupyter example can be found [here](https://gist.github.com/dvandyk/cea53e8283dd3b2ecb3c4f3cd8cc0c5a#file-goodness-of-fit-test-ipynb).

### CODE REVIEW

**Comment by dvandyk** [comment]
I have added e007999 to fix problems on MacOS X. It seems the newest version of SciPy has removed ```scipy.interpolate.spline```. Replaced with ```scipy.interpolate.CubicSpline```.

**Comment by dvandyk** [comment]
88b56da now calculate the total degrees of freedom correctly.

**Comment by fredRos** [comment]
Hey I just saw this PR. Given it's merged already, I guess I don't review any more??

**Comment by dvandyk** [comment]
> Hey I just saw this PR. Given it's merged already, I guess I don't review any more??

I went through 3 iterations myself, and used it for some preliminary study on Lambda_b -> Lambda mu mu. Should be fine now.

**Pull request merged**
