### PR TITLE
Stop using Minuit2

### PR DESCRIPTION
**Pull request by dvandyk**
Not being able to download the Minuit2 source code on a new laptop focuses the mind brilliantly...

### CODE REVIEW

**Review by mreboud — APPROVED** [review]
We still need to update the documentation, right?

**Comment by dvandyk** [comment]
@mreboud good point. Wanna try your hand?

**Comment by mreboud** [comment]
Yes, I just need to remove all instance of Minuit2, right?

**Comment by dvandyk** [comment]
I think so!

**Comment by dvandyk** [comment]
@mreboud will merge it right now, we just need to keep in mind to fix the documentation before the next release.

**Pull request merged**
