### PR TITLE
Solves issue 714 and 715

### PR DESCRIPTION
**Pull request by mreboud**
Solves #714
Solves #715

### CODE REVIEW

**Review by MJKirk — APPROVED** [review]
Looks good to me!

**Comment by mreboud** [comment]
> Looks good to me!

Thanks, I just remove the cells and python version modification in the notebook, and the we can merge. Unless @dvandyk has a comment?

**Review by dvandyk — CHANGES_REQUESTED** [review]
I think the poles are incorrect in the description.

**Comment by mreboud** [comment]
> I think the poles are incorrect in the description.

They should match BSZ's right?

image

**Comment by dvandyk** [comment]
The form is OK, but the states are listed as ``D^*`` mesons:
image
They should be generic poles or (in this example) ``B_c`` states with a variety of spin/parity quantum numbers.
I would replace this with ``m_{R_i}^2`` and explain that the poles are listed in the respective papers.

**Comment by mreboud** [comment]
> The form is OK, but the states are listed as `D^*` mesons: image They should be generic poles or (in this example) `B_c` states with a variety of spin/parity quantum numbers. I would replace this with `m_{R_i}^2` and explain that the poles are listed in the respective papers.

Ah sure sorry, I am an idiot

**Review by dvandyk — APPROVED** [review]

**Pull request merged**
