### PR TITLE
All the changes from Issue196

### PR DESCRIPTION
**Pull request by DomLeljak**
@dvandyk The fixup for #275 is in e6d13c4 and c829b01.

There's a lot of stuff, probably a lot of conflicts, let me know if you want to do it together.

### CODE REVIEW

**Comment by DomLeljak** [comment]
I just realized, probably should have compared to dvandyk/eos at issue196 first...

**Review by cBobeth — COMMENTED** [review]
Please correct also line 276 in b-to-psd-l-nu.cc

**Comment by DomLeljak** [comment]
Missed line 276 while patching... Thanks.

**Comment by dvandyk** [comment]
We cleaned this up. @cBobeth we fixed line 276 in the process. Thanks for the heads up!

**Comment by cBobeth** [comment]
I did not yet check whether there are some other issues. There is the 1/m_lep^2 singularity in the amplitude H_tS, which we could make explicit, as in B->D* lv, but this can also be a separate commit.

**Comment by dvandyk** [comment]
@cBobeth this is what we used for our recent paper, so I'd like to have it in the master repository if it passes the tests, which it did.

**Comment by cBobeth** [comment]
@dvandyk: Yes, it can be a separate commit. Since it is just rewriting equivalently, all test cases should not be affected.

**Pull request merged**
